Repository team-aliens/DMS-Android, pull requests merged in 2022-10, with the labels that each got.

#19 Merge: Design System Button
  design-system/src/main/java/com/example/design_system/button/basicbutton.kt
  design-system/src/main/java/com/example/design_system/button/button.kt
  design-system/src/main/java/com/example/design_system/button/checkbox.kt
  design-system/src/main/java/com/example/design_system/button/toggleswitch.kt
  design-system/src/main/java/com/example/design_system/component/.gitkeep
  design-system/src/main/java/com/example/design_system/icon/icons.kt
  design-system/src/main/java/com/example/design_system/modifier/clickable.kt
  design-system/src/main/java/com/example/design_system/modifier/shadow.kt
  design-system/src/main/java/com/example/design_system/typography/typography.kt
  design-system/src/main/java/com/example/design_system/utils/runIf.kt
  design-system/src/main/res/drawable/ic_applicate.xml
  design-system/src/main/res/drawable/ic_backward.xml
  design-system/src/main/res/drawable/ic_breakfast.xml
  design-system/src/main/res/drawable/ic_calender.xml
  design-system/src/main/res/drawable/ic_check.xml
  design-system/src/main/res/drawable/ic_close.xml
  design-system/src/main/res/drawable/ic_dinner.xml
  design-system/src/main/res/drawable/ic_home.xml
  design-system/src/main/res/drawable/ic_invisible.xml
  design-system/src/main/res/drawable/ic_launch.xml
  design-system/src/main/res/drawable/ic_mypage.xml
  design-system/src/main/res/drawable/ic_notice.xml
  design-system/src/main/res/drawable/ic_plus.xml
  design-system/src/main/res/drawable/ic_sort.xml
  design-system/src/main/res/drawable/ic_visible.xml
Labels: feat

#27 🔀 :: Dorm Notice
  design-system/src/main/java/com/example/design_system/button/button.kt
  design-system/src/main/java/com/example/design_system/button/checkbox.kt
  design-system/src/main/java/com/example/design_system/component/.gitkeep
Labels: feat, Dorm

#24 🔀 :: DormDialog
  design-system/src/main/java/com/example/design_system/dialog/dialog.kt
Labels: feat

#29 🔀 :: DormSurvey
  design-system/src/main/java/com/example/design_system/button/toggleswitch.kt
  design-system/src/main/java/com/example/design_system/component/survey.kt
  design-system/src/main/java/com/example/design_system/modifier/shadow.kt
Labels: feat, Dorm

#31 🔀 :: DormNotice
  design-system/src/main/java/com/example/design_system/component/notice.kt
Labels: feat, Dorm

#33 🔀 :: DormLostProperty
  design-system/build.gradle.kts
  design-system/src/main/AndroidManifest.xml
  design-system/src/main/java/com/example/design_system/component/lostproperty.kt
Labels: feat, Dorm

#35 🔀 :: dorm vote
  design-system/src/main/java/com/example/design_system/component/vote.kt
Labels: feat, Dorm

#39 🔀 :: DormTextField
  design-system/src/main/java/com/example/design_system/button/basicbutton.kt
  design-system/src/main/java/com/example/design_system/component/lostproperty.kt
  design-system/src/main/java/com/example/design_system/component/notice.kt
  design-system/src/main/java/com/example/design_system/component/survey.kt
  design-system/src/main/java/com/example/design_system/dialog/dialog.kt
  design-system/src/main/java/com/example/design_system/icon/icons.kt
  design-system/src/main/java/com/example/design_system/textfield/textfield.kt
  design-system/src/main/java/com/example/design_system/theme/theme.kt
  design-system/src/main/res/drawable/ic_password_invisible.xml
  design-system/src/main/res/drawable/ic_password_visible.xml
Labels: feat, Dorm

#37 🔀 :: DormPhoto
  design-system/src/main/java/com/example/design_system/animate/animationbox.kt
  design-system/src/main/java/com/example/design_system/component/photo.kt
  design-system/src/main/res/drawable/ic_photo_close.xml
Labels: feat, Dorm

#26 🔀 :: Login Business Logic
  auth_data/src/main/java/com/example/auth_data/.gitkeep
  auth_data/src/main/java/com/example/auth_data/remote/api/UserApi.kt
  auth_data/src/main/java/com/example/auth_data/remote/datasource/declaration/RemoteUserDataSource.kt
  auth_data/src/main/java/com/example/auth_data/remote/datasource/implementation/RemoteUserDataSourceImpl.kt
  auth_data/src/main/java/com/example/auth_data/remote/request/SignInRequest.kt
  auth_data/src/main/java/com/example/auth_data/remote/response/SignInResponse.kt
  auth_data/src/main/java/com/example/auth_data/remote/url/DmsUrl.kt
  auth_data/src/main/java/com/example/auth_data/repository/UserRepositoryImpl.kt
  auth_data/src/main/java/com/example/auth_data/util/HttpHandler.kt
  auth_domain/build.gradle.kts
  auth_domain/src/main/java/com/example/auth_domain/.gitkeep
  auth_domain/src/main/java/com/example/auth_domain/entity/UserVisibleEntity.kt
  auth_domain/src/main/java/com/example/auth_domain/exception/Basic.kt
  auth_domain/src/main/java/com/example/auth_domain/exception/User.kt
  auth_domain/src/main/java/com/example/auth_domain/param/LoginParam.kt
  auth_domain/src/main/java/com/example/auth_domain/repository/UserRepository.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/RemoteSignInUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/UseCase.kt
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Versions.kt
  gradle/wrapper/gradle-wrapper.properties
  local_database/src/main/java/com/example/local_database/.gitkeep
  local_database/src/main/java/com/example/local_database/datasource/declaration/LocalUserDataSource.kt
  local_database/src/main/java/com/example/local_database/datasource/implementation/LocalUserDataSourceImpl.kt
  local_database/src/main/java/com/example/local_database/param/UserVisibleParam.kt
  local_database/src/main/java/com/example/local_database/repository/LocalUserRepositoryImpl.kt
  local_database/src/main/java/com/example/local_database/storage/declaration/UserDataStorage.kt
  local_database/src/main/java/com/example/local_database/storage/implementation/UserDataStorageImpl.kt
  local_domain/src/main/java/com/example/local_domain/.gitkeep
  local_domain/src/main/java/com/example/local_domain/entity/UserVisibleLocalEntity.kt
  local_domain/src/main/java/com/example/local_domain/entity/repository/LocalUserRepository.kt
Labels: feat

#43 🔀 :: issue & pr 템플릿 추가
  .github/ISSUE_TEMPLATE/do.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/Pull_Request_Template.yml
Labels: setting

#46 🔀 :: (#45) ToastDesignSystem
  design-system/src/main/java/com/example/design_system/toast/ToastMaker.kt
  design-system/src/main/java/com/example/design_system/toast/toast.kt
  design-system/src/main/res/drawable/ic_error_toast.png
  design-system/src/main/res/drawable/ic_information_toast.png
  design-system/src/main/res/drawable/ic_success_toast.png
Labels: feat

#50 🔀 :: (#49) Auth_Business_Logic
  auth_data/src/main/java/com/example/auth_data/remote/api/UserApi.kt
  auth_data/src/main/java/com/example/auth_data/remote/datasource/declaration/RemoteUserDataSource.kt
  auth_data/src/main/java/com/example/auth_data/remote/datasource/implementation/RemoteUserDataSourceImpl.kt
  auth_data/src/main/java/com/example/auth_data/remote/request/GetEmailCodeRequest.kt
  auth_data/src/main/java/com/example/auth_data/remote/url/DmsUrl.kt
  auth_data/src/main/java/com/example/auth_data/repository/UserRepositoryImpl.kt
  auth_domain/src/main/java/com/example/auth_domain/enum/EmailType.kt
  auth_domain/src/main/java/com/example/auth_domain/param/CheckEmailCodeParam.kt
  auth_domain/src/main/java/com/example/auth_domain/param/CompareEmailParam.kt
  auth_domain/src/main/java/com/example/auth_domain/param/RequestEmailCodeParam.kt
  auth_domain/src/main/java/com/example/auth_domain/repository/UserRepository.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/auth/RefreshTokenUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/auth/RemoteCheckEmailUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/auth/RemoteCheckIdUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/auth/RemoteCompareEmailUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/auth/RemoteRequestEmailCodeUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/auth/RemoteSignInUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/auth/RemoteSignUpUseCase.kt
Labels: feat

#51 🔀 :: (#47) Login View Logic
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/example/dms_android/feature/auth/login/LoginScreen.kt
  presentation/src/main/res/drawable/temporarylogo.png
  presentation/src/main/res/values/strings.xml
Labels: feat

#53 🔀 :: (#52) LoginViewModel Logic
  auth_data/src/main/java/com/example/auth_data/util/HttpHandler.kt
  auth_domain/src/main/java/com/example/auth_domain/exception/Basic.kt
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Versions.kt
  design-system/src/main/java/com/example/design_system/toast/ToastMaker.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/example/dms_android/base/BaseViewModel.kt
  presentation/src/main/java/com/example/dms_android/base/MviEvent.kt
  presentation/src/main/java/com/example/dms_android/base/MviState.kt
  presentation/src/main/java/com/example/dms_android/base/Reducer.kt
  presentation/src/main/java/com/example/dms_android/feature/MainActivity.kt
  presentation/src/main/java/com/example/dms_android/feature/auth/login/LoginScreen.kt
  presentation/src/main/java/com/example/dms_android/feature/auth/login/SignInEvent.kt
  presentation/src/main/java/com/example/dms_android/feature/auth/login/SignInState.kt
  presentation/src/main/java/com/example/dms_android/util/EventFlow.kt
  presentation/src/main/java/com/example/dms_android/viewmodel/auth/login/SignInViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: feat

#58 🔀 :: (#56)First Sprint Change Password View
  presentation/src/main/java/com/example/dms_android/feature/auth/changepassword/ChangePasswordScreen.kt
  presentation/src/main/res/drawable/ic_baseline_arrow_back_24.xml
  presentation/src/main/res/values/strings.xml
Labels: feat

#62 Merge: (#61) update typography
  design-system/src/main/java/com/example/design_system/component/lostproperty.kt
  design-system/src/main/java/com/example/design_system/component/notice.kt
  design-system/src/main/java/com/example/design_system/component/vote.kt
  design-system/src/main/java/com/example/design_system/icon/icons.kt
  design-system/src/main/java/com/example/design_system/textfield/textfield.kt
  design-system/src/main/java/com/example/design_system/typography/typography.kt
  presentation/src/main/java/com/example/dms_android/base/BaseViewModel.kt
  presentation/src/main/java/com/example/dms_android/feature/MainActivity.kt
  presentation/src/main/java/com/example/dms_android/feature/auth/login/LoginScreen.kt
  presentation/src/main/java/com/example/dms_android/feature/auth/login/SignInEvent.kt
  presentation/src/main/java/com/example/dms_android/viewmodel/auth/login/SignInViewModel.kt
Labels: feat, refactor, Dorm

#65 🔀 :: (#59) First Sprint ChangePassword ViewModel
  auth_data/src/main/java/com/example/auth_data/remote/api/ManagersApi.kt
  auth_data/src/main/java/com/example/auth_data/remote/datasource/declaration/RemoteStudentsDataSource.kt
  auth_data/src/main/java/com/example/auth_data/remote/datasource/implementation/RemoteStudentsDataSourceImpl.kt
  auth_data/src/main/java/com/example/auth_data/repository/StudentsRepositoryImpl.kt
  auth_domain/src/main/java/com/example/auth_domain/param/FindIdParam.kt
  auth_domain/src/main/java/com/example/auth_domain/repository/StudentsRepository.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/students/RemoteChangePasswordUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/students/RemoteFindIdUseCase.kt
  presentation/src/main/java/com/example/dms_android/feature/auth/changepassword/ChangePasswordEvent.kt
  presentation/src/main/java/com/example/dms_android/feature/auth/changepassword/ChangePasswordScreen.kt
  presentation/src/main/java/com/example/dms_android/feature/auth/changepassword/ChangePasswordState.kt
  presentation/src/main/java/com/example/dms_android/feature/register/screen/ConfirmSchoolScreen.kt
  presentation/src/main/java/com/example/dms_android/viewmodel/changepw/ChangePasswordViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: feat

#66 🔀 :: FirstSprint Make Term View
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/example/dms_android/feature/register/screen/PolicyScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: feat

#70 🔀 :: (#69) First Sprint applicate profile image view
  design-system/src/main/java/com/example/design_system/color/colors.kt
  design-system/src/main/java/com/example/design_system/icon/icons.kt
  design-system/src/main/res/drawable/ic_backarrow.png
  presentation/src/main/java/com/example/dms_android/feature/register/screen/ProfileImageScreen.kt
  presentation/src/main/res/drawable-v24/addimage.png
  presentation/src/main/res/drawable-v24/addplusimage.png
  presentation/src/main/res/values/strings.xml
Labels: feat

#74 🔀 :: FirstSprint Make EmailVerification, SchoolVerification View
  presentation/src/main/java/com/example/dms_android/feature/register/screen/EmailVerificationScreen.kt
  presentation/src/main/java/com/example/dms_android/feature/register/screen/SchoolVerification.kt
  presentation/src/main/java/com/example/dms_android/feature/register/screen/component/OtpView.kt
  presentation/src/main/res/values/strings.xml
Labels: feat

#79 🔀 :: FirstSprint Self-confirmation and authentication View
  presentation/src/main/java/com/example/dms_android/feature/auth/selfconfirmation/SelfConfirmScreen.kt
  presentation/src/main/java/com/example/dms_android/feature/auth/selfconfirmation/VeritificationScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: feat

#78 🔀 :: FirstSprint Make Register ViewModel
  auth_domain/src/main/java/com/example/auth_domain/param/RegisterParam.kt
  presentation/src/main/java/com/example/dms_android/feature/register/event/SignUpEvent.kt
  presentation/src/main/java/com/example/dms_android/feature/register/state/SignUpState.kt
  presentation/src/main/java/com/example/dms_android/viewmodel/auth/register/SignUpViewModel.kt
Labels: feat

#76 🔀 :: (#71) ImageScreen Impl
  auth_domain/src/main/java/com/example/auth_domain/enum/BottomSheetType.kt
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/example/dms_android/feature/register/screen/ProfileImageScreen.kt
  presentation/src/main/java/com/example/dms_android/util/TedImagePicker.kt
  presentation/src/main/res/drawable-v24/ic_camera.png
  presentation/src/main/res/drawable-v24/ic_photo.png
  presentation/src/main/res/values/strings.xml
Labels: feat

#90 🔀 :: Confirm Email Authentication Number - diffrent param Value
  auth_data/src/main/java/com/example/auth_data/repository/UserRepositoryImpl.kt
  auth_domain/src/main/java/com/example/auth_domain/param/CheckEmailCodeParam.kt
Labels: 👾bug

#87 🔀 :: FirstSprint Auth - Schools Logic
  auth_data/src/main/java/com/example/auth_data/remote/api/SchoolsApi.kt
  auth_data/src/main/java/com/example/auth_data/remote/datasource/declaration/RemoteSchoolsDataSource.kt
  auth_data/src/main/java/com/example/auth_data/remote/datasource/implementation/RemoteSchoolsDataSourceImpl.kt
  auth_data/src/main/java/com/example/auth_data/remote/response/schools/SchoolConfirmQuestionResponse.kt
  auth_data/src/main/java/com/example/auth_data/remote/response/schools/SchoolIdResponse.kt
  auth_data/src/main/java/com/example/auth_data/remote/url/DmsUrl.kt
  auth_data/src/main/java/com/example/auth_data/repository/SchoolsRepositoryImpl.kt
  auth_domain/src/main/java/com/example/auth_domain/entity/SchoolConfirmQuestionEntity.kt
  auth_domain/src/main/java/com/example/auth_domain/entity/SchoolIdEntity.kt
  auth_domain/src/main/java/com/example/auth_domain/param/SchoolAnswerParam.kt
  auth_domain/src/main/java/com/example/auth_domain/repository/SchoolsRepository.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/schools/RemoteSchoolAnswerUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/schools/RemoteSchoolCodeUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/schools/RemoteSchoolQuestionUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/students/RemoteResetPasswordUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/students/RemoteSignUpUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/students/duplicateCheckEmailUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/students/duplicateCheckIdUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/user/RefreshTokenUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/user/RemoteCheckEmailUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/user/RemoteCheckIdUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/user/RemoteCompareEmailUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/user/RemoteRequestEmailCodeUseCase.kt
  auth_domain/src/main/java/com/example/auth_domain/usecase/user/RemoteSignInUseCase.kt
  presentation/src/main/java/com/example/dms_android/viewmodel/auth/login/SignInViewModel.kt
  presentation/src/main/java/com/example/dms_android/viewmodel/auth/register/SignUpViewModel.kt
  presentation/src/main/java/com/example/dms_android/viewmodel/changepw/ChangePasswordViewModel.kt
Labels: feat, refactor

#92 🔀 :: (#91) Develope Error Catching
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/ProjectProperties.kt
  buildSrc/src/main/kotlin/Versions.kt
  di/build.gradle.kts
  di/src/main/java/com/example/di/NetWorkModule.kt
  feature_data/build.gradle.kts
  gradle.properties
  local_database/build.gradle.kts
  presentation/build.gradle.kts
Labels: feat
