Repository team-aliens/DMS-Android, pull requests merged in 2023-05, with the labels that each got.

#395 🔀 :: (#350) buildsrc 상수 수정 및 버전 업데이트
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/BuildPlugins.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Dependency.kt
  buildSrc/src/main/kotlin/Plugins.kt
  buildSrc/src/main/kotlin/ProjectProperties.kt
  buildSrc/src/main/kotlin/Versions.kt
  data/build.gradle.kts
  design-system/build.gradle.kts
  design-system/src/main/java/team/aliens/design_system/component/lostproperty.kt
  design-system/src/main/java/team/aliens/design_system/component/photo.kt
  di/build.gradle.kts
  domain/build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  local/build.gradle.kts
  local/src/main/java/team/aliens/local/room/dao/MealDao.kt
  local/src/main/java/team/aliens/local/room/dao/NoticeDao.kt
  local_database/build.gradle.kts
  local_domain/build.gradle.kts
  presentation/build.gradle.kts
  presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/last/EnterProfileImageFragment.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/last/PolicyFragment.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/last/dialog/SignUpSuccessDialog.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/password/EnterPasswordFragment.kt
  presentation/src/main/java/team/aliens/dms_android/viewmodel/changepw/ChangePasswordViewModel.kt
  presentation/src/main/res/layout/fragment_sign_up_confirm_school_question.xml
  presentation/src/main/res/layout/fragment_sign_up_confirm_verification_code_email.xml
  presentation/src/main/res/layout/fragment_sign_up_confirm_verification_code_school.xml
  presentation/src/main/res/layout/fragment_sign_up_enter_email.xml
  presentation/src/main/res/layout/fragment_sign_up_enter_id.xml
  presentation/src/main/res/layout/fragment_sign_up_enter_password.xml
  presentation/src/main/res/layout/fragment_sign_up_enter_profile_image.xml
  presentation/src/main/res/layout/fragment_sign_up_policy.xml
  remote/build.gradle.kts
Labels: setting

#396 🔀 :: (#394) 전역 토스트 관리 기능 구현
  design-system/src/main/java/team/aliens/design_system/toast/toast.kt
  presentation/src/main/java/team/aliens/dms_android/feature/MainActivity.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/RootDms.kt
Labels: feat

#399 🔀 :: (#349) gitignore 파일 업데이트 및 ignore될 파일 삭제
  .gitignore
  .idea/compiler.xml
  .idea/gradle.xml
Labels: setting

#401 🔀 :: (#398) 뷰모델 패키지 구조 변경
  presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/changepassword/ChangePasswordIdentificationScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/changepassword/ChangePasswordScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/changepassword/ChangePasswordVerifyEmailScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/changepassword/ChangePasswordViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/comparepassword/ComparePasswordScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/login/SignInViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/MealContent.kt
  presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/MealViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/image/ConfirmImageScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/image/ConfirmImageViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageChangePasswordScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/RootViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeDetailScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/RegisterEmailViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/SignUpEmailScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/SignUpEmailVerifyScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/id/SetIdViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/id/SignUpIdScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/last/SignUpPolicyScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/last/SignUpProfileScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/last/SignUpViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/school/ConfirmSchoolViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/school/ExamineSchoolCodeViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/school/SignUpSchoolQuestionScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/school/SignUpVerifySchoolScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailUiState.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsViewModel.kt
Labels: refactor

#403 🔀 :: (#402) rootdms navhost 리팩토링
  design-system/src/main/java/team/aliens/design_system/toast/toast.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/team/aliens/dms_android/constans/Extra.kt
  presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/changepassword/ChangePasswordIdentificationScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/changepassword/ChangePasswordScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/changepassword/ResetPasswordScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/comparepassword/ComparePasswordScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/findid/FindIdScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/login/SignInScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/image/UploadProfileImageScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageChangePasswordScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/AuthNavigation.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/BottomNavigationItem.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsRoute.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/HomeNavigation.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/NavigationRoute.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/RootDms.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/RootViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/SignUpNavigation.kt
  presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeDetailsScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointHistoryScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/SignUpEmailVerificationCodeScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/SignUpSendVerificationEmailScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/id/SignUpSetIdScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/last/SignUpPolicyScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/last/SignUpSetProfileImageScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/password/SignUpSetPasswordScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/school/SignUpSchoolVerificationQuestionScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/school/SignUpVerifySchoolScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainsApplicationScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/splash/SplashScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomsScreen.kt
Labels: refactor

#408 🔀 :: (#405) baseviewmodel 구현
  presentation/src/main/java/team/aliens/dms_android/_base/BaseViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/_base/MviViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/_base/UiEvent.kt
  presentation/src/main/java/team/aliens/dms_android/_base/UiState.kt
  presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailUiState.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListUiState.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListViewModel.kt
Labels: feat, refactor

#409 🔀 :: (#406) dmsappstate 구현
  presentation/src/main/java/team/aliens/dms_android/feature/application/DmsAppState.kt
Labels: feat

#410 🔀 :: (#407) 자습실 패키지 screen 리팩토링
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomsScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: refactor

#412 🔀 :: (#406) dmsappstate 구현
  design-system/src/main/java/team/aliens/design_system/toast/toast.kt
  presentation/src/main/java/team/aliens/dms_android/feature/application/DmsAppState.kt
  presentation/src/main/java/team/aliens/dms_android/util/manager/DialogManager.kt
  presentation/src/main/java/team/aliens/dms_android/util/manager/ToastManager.kt
Labels: refactor

#425 🔀 :: (#424) 급식 스크린 리팩토링
  design-system/src/main/java/team/aliens/design_system/component/calender.kt
  design-system/src/main/java/team/aliens/design_system/modifier/clickable.kt
  design-system/src/main/java/team/aliens/design_system/utils/dateUtil.kt
  presentation/src/main/java/team/aliens/dms_android/feature/Home.kt
  presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaMenu.kt
  presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/MealContent.kt
  presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/MealEvent.kt
  presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/MealState.kt
  presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/MealViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/meal/MealScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/meal/MealViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: performance, refactor

#421 🔀 :: (#418) sign in 리팩토링
  design-system/src/main/java/team/aliens/design_system/button/basicbutton.kt
  domain/src/main/java/team/aliens/domain/exception/AuthException.kt
  domain/src/main/java/team/aliens/domain/model/student/Feature.kt
  presentation/src/main/java/team/aliens/dms_android/base/MviViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/common/CompositionLocal.kt
  presentation/src/main/java/team/aliens/dms_android/component/AppLogo.kt
  presentation/src/main/java/team/aliens/dms_android/feature/application/DmsAppState.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInEvent.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInState.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInViewEffect.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/AuthNavigation.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt
  presentation/src/main/res/values/strings.xml
  remote/src/main/java/team/aliens/remote/datasource/RemoteAuthDataSourceImpl.kt
Labels: performance, refactor

#428 🔀 :: (#426) 상벌점 내역 확인 스크린 리팩토링
  domain/src/main/java/team/aliens/domain/model/point/FetchPointsOutput.kt
  presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageState.kt
  presentation/src/main/java/team/aliens/dms_android/feature/mypage/pointhistory/PointHistoryScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/mypage/pointhistory/PointHistoryViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/HomeNavigation.kt
  presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointHistoryScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointList.kt
  presentation/src/main/res/drawable/img_dummy.jpg
  presentation/src/main/res/values/strings.xml
  remote/src/main/java/team/aliens/remote/model/point/FetchPointsResponse.kt
Labels: refactor
