Repository team-aliens/DMS-Android, pull requests merged in 2023-06, with the labels that each got.

#432 🔀 :: (#427) authorizationinterceptor 수정
  data/src/main/java/team/aliens/data/datasource/local/LocalAuthDataSource.kt
  data/src/main/java/team/aliens/data/facade/AuthorizationFacade.kt
  data/src/main/java/team/aliens/data/manager/TokenReissueManager.kt
  data/src/main/java/team/aliens/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/team/aliens/data/util/DateUtil.kt
  design-system/src/main/java/team/aliens/design_system/toast/toast.kt
  di/src/main/java/team/aliens/di/facade/FacadeModule.kt
  di/src/main/java/team/aliens/di/manager/ManagerModule.kt
  di/src/main/java/team/aliens/di/remote/HttpModule.kt
  local/src/main/java/team/aliens/local/datasource/LocalAuthDataSourceImpl.kt
  presentation/src/main/java/team/aliens/dms_android/feature/MainActivity.kt
  presentation/src/main/java/team/aliens/dms_android/feature/application/DmsAppState.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt
  presentation/src/main/java/team/aliens/dms_android/handler/DmsExceptionHandler.kt
  remote/src/main/java/team/aliens/remote/http/AuthorizationInterceptor.kt
  remote/src/main/java/team/aliens/remote/http/TokenReissueClient.kt
  remote/src/main/java/team/aliens/remote/http/TokenReissueManagerImpl.kt
Labels: performance, refactor

#422 🔀 :: (#420) 잔류 신청 리팩토링
  design-system/src/main/java/team/aliens/design_system/button/basicbutton.kt
  design-system/src/main/java/team/aliens/design_system/component/LastAppliedItem.kt
  domain/src/main/java/team/aliens/domain/model/remains/CurrentAppliedRemainsOption.kt
  domain/src/main/java/team/aliens/domain/model/remains/FetchCurrentAppliedRemainsOptionOutput.kt
  domain/src/main/java/team/aliens/domain/model/remains/FetchRemainsApplicationTimeOutput.kt
  domain/src/main/java/team/aliens/domain/model/remains/FetchRemainsOptionsOutput.kt
  domain/src/main/java/team/aliens/domain/usecase/remain/FetchCurrentAppliedRemainsOptionUseCase.kt
  domain/src/main/java/team/aliens/domain/usecase/remain/FetchRemainsApplicationTimeUseCase.kt
  domain/src/main/java/team/aliens/domain/usecase/remain/FetchRemainsOptionsUseCase.kt
  presentation/src/main/java/team/aliens/dms_android/component/Brush.kt
  presentation/src/main/java/team/aliens/dms_android/component/FloatingNotice.kt
  presentation/src/main/java/team/aliens/dms_android/feature/mypage/pointhistory/PointHistoryScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/HomeNavigation.kt
  presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationEvent.kt
  presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationState.kt
  presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainsApplicationScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/remains/RemainsApplicationScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/remains/RemainsApplicationViewModel.kt
  presentation/src/main/res/values/strings.xml
  remote/src/main/java/team/aliens/remote/model/remains/FetchCurrentAppliedRemainsOptionResponse.kt
  remote/src/main/java/team/aliens/remote/model/remains/FetchRemainsOptionsResponse.kt
Labels: refactor

#435 🔀 :: (#413) 공지사항 로직 리팩토링
  data/src/main/java/team/aliens/data/repository/NoticeRepositoryImpl.kt
  design-system/src/main/java/team/aliens/design_system/component/notice.kt
  domain/src/main/java/team/aliens/domain/model/notice/FetchNoticesOutput.kt
  domain/src/main/java/team/aliens/domain/model/notice/Notice.kt
  domain/src/main/java/team/aliens/domain/usecase/notice/FetchNoticesUseCase.kt
  local/src/main/java/team/aliens/local/room/entity/NoticeEntity.kt
  presentation/src/main/java/team/aliens/dms_android/feature/Home.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/HomeNavigation.kt
  presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeDetailsScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeDetailsViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeEvent.kt
  presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeState.kt
  presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticesViewModel.kt
Labels: refactor

#445 🔀 :: (#444) mvi viewmodel 구현
  presentation/src/main/java/team/aliens/dms_android/base/BaseMviViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/base/MviIntent.kt
  presentation/src/main/java/team/aliens/dms_android/base/MviSingleEvent.kt
  presentation/src/main/java/team/aliens/dms_android/base/MviViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/base/MviViewState.kt
  presentation/src/main/java/team/aliens/dms_android/base/UiEvent.kt
  presentation/src/main/java/team/aliens/dms_android/base/UiState.kt
Labels: feat, refactor

#448 🔀:: (#447) 안드로이드 6.0 호환
  buildSrc/src/main/kotlin/ProjectProperties.kt
  design-system/src/main/java/team/aliens/design_system/modifier/shadow.kt
  domain/src/main/java/team/aliens/domain/model/_common/DayOfWeek.kt
  domain/src/main/java/team/aliens/domain/model/remains/FetchRemainsApplicationTimeOutput.kt
  domain/src/main/java/team/aliens/domain/model/remains/RemainsApplicationTime.kt
  presentation/src/main/java/team/aliens/dms_android/DmsApp.kt
  presentation/src/main/java/team/aliens/dms_android/DmsAppState.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/home/Home.kt
  presentation/src/main/java/team/aliens/dms_android/feature/home/HomeNavigation.kt
  presentation/src/main/java/team/aliens/dms_android/feature/remains/RemainsApplicationScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsScreen.kt
  presentation/src/main/java/team/aliens/dms_android/widget/meal/MealService.kt
  presentation/src/main/java/team/aliens/dms_android/widget/meal/MealState.kt
  presentation/src/main/java/team/aliens/dms_android/widget/meal/MealType.kt
  presentation/src/main/java/team/aliens/dms_android/widget/meal/provider/BaseMealWidgetProvider.kt
  remote/src/main/java/team/aliens/remote/model/remains/FetchRemainsApplicationTimeResponse.kt
Labels: feat, setting

#449 🔀 :: (#444) mvi viewmodel 수정
  presentation/src/main/java/team/aliens/dms_android/base/BaseMviViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/base/BaseViewModel1.kt
  presentation/src/main/java/team/aliens/dms_android/base/MviSideEffect.kt
  presentation/src/main/java/team/aliens/dms_android/base/MviState.kt
  presentation/src/main/java/team/aliens/dms_android/base/MviViewState.kt
  presentation/src/main/java/team/aliens/dms_android/base/Reducer.kt
  presentation/src/main/java/team/aliens/dms_android/base/_MviState.kt
  presentation/src/main/java/team/aliens/dms_android/extension/rememberFlowWithLifeCycle.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/changepassword/ChangePasswordState.kt
  presentation/src/main/java/team/aliens/dms_android/feature/image/ConfirmImageState.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomState.kt
Labels: feat, refactor

#454 🔀 :: (#453) target sdk 버전 변경
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: setting

#460 🔀 :: (#445) exception 클래스 구현
  domain/src/main/java/team/aliens/domain/exception/AuthException.kt
  domain/src/main/java/team/aliens/domain/exception/CommonException.kt
  domain/src/main/java/team/aliens/domain/exception/LocalException.kt
  domain/src/main/java/team/aliens/domain/exception/NoticeException.kt
  domain/src/main/java/team/aliens/domain/exception/RemainsException.kt
  domain/src/main/java/team/aliens/domain/exception/RemoteException.kt
  domain/src/main/java/team/aliens/domain/exception/SchoolException.kt
  domain/src/main/java/team/aliens/domain/exception/StudentException.kt
  domain/src/main/java/team/aliens/domain/exception/StudyRoomException.kt
Labels: feat

#462 🔀 :: (#459) toast 구현
  design-system/src/main/java/team/aliens/design_system/icon/icons.kt
  design-system/src/main/java/team/aliens/design_system/toast/toast.kt
  design-system/src/main/res/drawable/ic_check.xml
  design-system/src/main/res/drawable/ic_error_toast.png
  design-system/src/main/res/drawable/ic_information.xml
  design-system/src/main/res/drawable/ic_information_toast.png
  design-system/src/main/res/drawable/ic_warning.xml
  presentation/src/main/java/team/aliens/dms_android/DmsApp.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/changepassword/ChangePasswordScreen.kt
Labels: refactor

#463 🔀 :: (#459) local toast 구현
  design-system/src/main/java/team/aliens/design_system/toast/toast.kt
  presentation/src/main/java/team/aliens/dms_android/DmsApp.kt
  presentation/src/main/java/team/aliens/dms_android/MainActivity.kt
  presentation/src/main/java/team/aliens/dms_android/common/CompositionLocal.kt
  presentation/src/main/java/team/aliens/dms_android/util/compose/Toast.kt
Labels: feat

#464 🔀 :: (#458) sign in 재구성
  domain/src/main/java/team/aliens/domain/exception/RemoteException.kt
  presentation/src/main/java/team/aliens/dms_android/base/BaseMviViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/common/CompositionLocal.kt
  presentation/src/main/java/team/aliens/dms_android/extension/rememberFlowWithLifeCycle.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/AuthNavigation.kt
  presentation/src/main/java/team/aliens/dms_android/feature/signin/SignInScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/signin/SignInViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: refactor
