Repository team-aliens/DMS-Android, pull requests merged in 2023-04, with the labels that each got.

#348 🔀 :: (#344) 비활성화 기능 구현
  data/src/main/java/team/aliens/data/remote/response/user/SignInResponse.kt
  data/src/main/java/team/aliens/data/repository/UserRepositoryImpl.kt
  local_database/src/main/java/team/aliens/local_database/datasource/declaration/LocalUserDataSource.kt
  local_database/src/main/java/team/aliens/local_database/datasource/implementation/LocalUserDataSourceImpl.kt
  local_database/src/main/java/team/aliens/local_database/param/FeaturesParam.kt
  local_database/src/main/java/team/aliens/local_database/param/UserPersonalKeyParam.kt
  local_database/src/main/java/team/aliens/local_database/param/UserVisibleParam.kt
  local_database/src/main/java/team/aliens/local_database/repository/LocalUserRepositoryImpl.kt
  local_database/src/main/java/team/aliens/local_database/storage/declaration/UserDataStorage.kt
  local_database/src/main/java/team/aliens/local_database/storage/implementation/UserDataStorageImpl.kt
  local_domain/src/main/java/team/aliens/local_domain/entity/UserKeyLocalEntity.kt
  local_domain/src/main/java/team/aliens/local_domain/entity/UserVisibleLocalEntity.kt
  local_domain/src/main/java/team/aliens/local_domain/entity/notice/UserVisibleInformEntity.kt
  local_domain/src/main/java/team/aliens/local_domain/param/FeaturesVisibleParam.kt
  local_domain/src/main/java/team/aliens/local_domain/repository/LocalUserRepository.kt
  local_domain/src/main/java/team/aliens/local_domain/usecase/uservisible/LocalUserVisibleInformUseCase.kt
  presentation/src/main/java/team/aliens/dms_android/common/CompositionLocal.kt
  presentation/src/main/java/team/aliens/dms_android/constans/Extra.kt
  presentation/src/main/java/team/aliens/dms_android/feature/MainActivity.kt
  presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/login/SignInState.kt
  presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt
  presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/splash/SplashScreen.kt
  presentation/src/main/java/team/aliens/dms_android/viewmodel/auth/login/SignInViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/viewmodel/root/RootViewModel.kt
Labels: feat

#346 🔀 :: (#345) deprecated design system
  design-system/src/main/java/team/aliens/design_system/animate/animationbox.kt
  design-system/src/main/java/team/aliens/design_system/annotation/DormDeprecated.kt
  design-system/src/main/java/team/aliens/design_system/button/button.kt
  design-system/src/main/java/team/aliens/design_system/button/checkbox.kt
  design-system/src/main/java/team/aliens/design_system/button/radiobutton.kt
  design-system/src/main/java/team/aliens/design_system/button/toggleswitch.kt
  design-system/src/main/java/team/aliens/design_system/color/colors.kt
  design-system/src/main/java/team/aliens/design_system/component/bottomsheet.kt
  design-system/src/main/java/team/aliens/design_system/component/calender.kt
  design-system/src/main/java/team/aliens/design_system/component/lostproperty.kt
  design-system/src/main/java/team/aliens/design_system/component/notice.kt
  design-system/src/main/java/team/aliens/design_system/component/photo.kt
  design-system/src/main/java/team/aliens/design_system/component/seat.kt
  design-system/src/main/java/team/aliens/design_system/component/survey.kt
  design-system/src/main/java/team/aliens/design_system/component/vote.kt
  design-system/src/main/java/team/aliens/design_system/dialog/dialog.kt
  design-system/src/main/java/team/aliens/design_system/icon/icons.kt
  design-system/src/main/java/team/aliens/design_system/modifier/background.kt
  design-system/src/main/java/team/aliens/design_system/modifier/clickable.kt
  design-system/src/main/java/team/aliens/design_system/modifier/shadow.kt
  design-system/src/main/java/team/aliens/design_system/textfield/textfield.kt
  design-system/src/main/java/team/aliens/design_system/theme/theme.kt
  design-system/src/main/java/team/aliens/design_system/typography/typography.kt
Labels: docs

#353 🔀 :: (#351) 자리 종류 보기 리팩토링
  data/src/main/java/team/aliens/data/remote/api/StudyRoomApi.kt
  data/src/main/java/team/aliens/data/remote/datasource/declaration/RemoteStudyRoomDataSource.kt
  data/src/main/java/team/aliens/data/remote/datasource/implementation/RemoteStudyRoomDataSourceImpl.kt
  data/src/main/java/team/aliens/data/repository/StudyRoomRepositoryImpl.kt
  design-system/src/main/java/team/aliens/design_system/component/seat.kt
  domain/src/main/java/team/aliens/domain/repository/StudyRoomRepository.kt
  domain/src/main/java/team/aliens/domain/usecase/studyroom/RemoteFetchStudyRoomSeatTypeUseCase.kt
  presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt
  presentation/src/main/java/team/aliens/dms_android/viewmodel/ApplicationViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt
Labels: refactor, 👾bug

#361 ⚡️ :: 버전 업데이트
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: setting

#364 🔀 :: (#362) 자습실 앱 바 이용시간 표시 로직 구현
  data/src/main/java/team/aliens/data/remote/response/studyroom/StudyRoomDetailResponse.kt
  data/src/main/java/team/aliens/data/repository/StudyRoomRepositoryImpl.kt
  domain/src/main/java/team/aliens/domain/entity/studyroom/StudyRoomDetailEntity.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomState.kt
  presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailUiState.kt
Labels: feat

#368 🔀 :: (#367) 로그인 후 처음 화면 진입시 비정상 종료 해결
  presentation/src/main/java/team/aliens/dms_android/common/CompositionLocal.kt
  presentation/src/main/java/team/aliens/dms_android/feature/MainActivity.kt
  presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt
Labels: 👾bug

#366 🔀 :: (#365) ci PROD_BASE_URL 구현
  .github/workflows/ci.yml
Labels: feat, setting

#372 🔀 :: (#371) 자습실 신청함 태그 구현
  data/src/main/java/team/aliens/data/remote/response/studyroom/StudyRoomListResponse.kt
  design-system/src/main/java/team/aliens/design_system/component/LastAppliedItem.kt
  design-system/src/main/java/team/aliens/design_system/component/seat.kt
  presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: feat

#377 🔀 :: (#376) 자습실 자리 취소 시 전체 취소 오류 수정
  data/src/main/java/team/aliens/data/remote/api/StudyRoomApi.kt
  data/src/main/java/team/aliens/data/remote/datasource/declaration/RemoteStudyRoomDataSource.kt
  data/src/main/java/team/aliens/data/remote/datasource/implementation/RemoteStudyRoomDataSourceImpl.kt
  data/src/main/java/team/aliens/data/remote/url/DmsUrl.kt
  data/src/main/java/team/aliens/data/repository/StudyRoomRepositoryImpl.kt
  domain/src/main/java/team/aliens/domain/param/CancelStudyRoomParam.kt
  domain/src/main/java/team/aliens/domain/repository/StudyRoomRepository.kt
  domain/src/main/java/team/aliens/domain/usecase/studyroom/RemoteCancelApplySeatUseCase.kt
  presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailScreen.kt
  presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt
Labels: 👾bug

#375 🔀 :: (#374) 회원가입 이메일 요청 중복 처리 예외 버그 수정
  presentation/src/main/java/team/aliens/dms_android/_base/BaseViewModel.kt
  presentation/src/main/java/team/aliens/dms_android/_base/ErrorEvent.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/SignUpEmailScreen.kt
  presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/SignUpEmailVerifyScreen.kt
  presentation/src/main/java/team/aliens/dms_android/viewmodel/auth/register/email/RegisterEmailViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: 👾bug

#379 🔀 :: (#378) 버전 업데이트
  buildSrc/src/main/kotlin/ProjectProperties.kt
Labels: setting

#389 🔀 :: (#386) service -> apiservice 이름 변경
  di/src/main/java/team/aliens/_di/remote/ServiceModule.kt
  remote/src/main/java/team/aliens/remote/apiservice/AuthApiService.kt
  remote/src/main/java/team/aliens/remote/apiservice/FileApiService.kt
  remote/src/main/java/team/aliens/remote/apiservice/MealApiService.kt
  remote/src/main/java/team/aliens/remote/apiservice/NoticeApiService.kt
  remote/src/main/java/team/aliens/remote/apiservice/PointApiService.kt
  remote/src/main/java/team/aliens/remote/apiservice/RemainsApiService.kt
  remote/src/main/java/team/aliens/remote/apiservice/SchoolApiService.kt
  remote/src/main/java/team/aliens/remote/apiservice/StudentApiService.kt
  remote/src/main/java/team/aliens/remote/apiservice/StudyRoomApiService.kt
  remote/src/main/java/team/aliens/remote/apiservice/UserApiService.kt
  remote/src/main/java/team/aliens/remote/datasource/RemoteAuthDataSourceImpl.kt
  remote/src/main/java/team/aliens/remote/datasource/RemoteFileDataSourceImpl.kt
  remote/src/main/java/team/aliens/remote/datasource/RemoteMealDataSourceImpl.kt
  remote/src/main/java/team/aliens/remote/datasource/RemoteNoticeDataSourceImpl.kt
  remote/src/main/java/team/aliens/remote/datasource/RemotePointDataSourceImpl.kt
  remote/src/main/java/team/aliens/remote/datasource/RemoteRemainsDataSourceImpl.kt
  remote/src/main/java/team/aliens/remote/datasource/RemoteSchoolDataSourceImpl.kt
  remote/src/main/java/team/aliens/remote/datasource/RemoteStudentDataSourceImpl.kt
  remote/src/main/java/team/aliens/remote/datasource/RemoteStudyRoomDataSourceImpl.kt
  remote/src/main/java/team/aliens/remote/datasource/RemoteUserDataSourceImpl.kt
Labels: refactor
